FROM node:latest as BUILD_STAGE
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx as PRODUCTION_STAGE
RUN mkdir /app
COPY --from=BUILD_STAGE /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf